package com.losmos.hrsnsauto.discovery;

public enum InstagramBrowserErrorCode {
	AUTOMATION_DISABLED,
	INVALID_CONFIGURATION,
	BROWSER_BUSY,
	BROWSER_BINARY_MISSING,
	BROWSER_PROFILE_IN_USE,
	LOGIN_REQUIRED,
	ACTION_REQUIRED,
	POST_UNAVAILABLE,
	AUTHOR_EXTRACTION_FAILED,
	PROFILE_UNAVAILABLE,
	NAVIGATION_TIMEOUT,
	UNEXPECTED_DOM,
	PERSISTENCE_FAILED
}
