CREATE TABLE candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instagram_username VARCHAR(30) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    profession VARCHAR(32) NOT NULL,
    specialty VARCHAR(100),
    follower_count INTEGER,
    hair_transplant_relation VARCHAR(32) NOT NULL,
    eligibility_status VARCHAR(32) NOT NULL,
    eligibility_reason VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_candidates_instagram_username UNIQUE (instagram_username),
    CONSTRAINT chk_candidates_username_lowercase
        CHECK (instagram_username = LOWER(instagram_username)),
    CONSTRAINT chk_candidates_profession
        CHECK (profession IN ('DOCTOR', 'PHARMACIST', 'KOREAN_MEDICINE', 'OTHER', 'UNKNOWN')),
    CONSTRAINT chk_candidates_follower_count
        CHECK (follower_count IS NULL OR follower_count >= 0),
    CONSTRAINT chk_candidates_hair_relation
        CHECK (hair_transplant_relation IN ('NOT_RELATED', 'RELATED', 'UNKNOWN')),
    CONSTRAINT chk_candidates_eligibility_status
        CHECK (eligibility_status IN ('ELIGIBLE', 'INELIGIBLE', 'REVIEW_REQUIRED'))
);

CREATE TABLE candidate_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    strength VARCHAR(16) NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    summary VARCHAR(1000) NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_candidate_evidence_candidate
        FOREIGN KEY (candidate_id) REFERENCES candidates (id) ON DELETE CASCADE,
    CONSTRAINT chk_candidate_evidence_type
        CHECK (type IN ('PROFESSION', 'IDENTITY', 'HAIR_TRANSPLANT', 'OTHER')),
    CONSTRAINT chk_candidate_evidence_strength
        CHECK (strength IN ('STRONG', 'WEAK'))
);

CREATE INDEX idx_candidate_evidence_candidate_id
    ON candidate_evidence (candidate_id);
