CREATE TABLE discovery_hashtags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_discovery_hashtags_keyword UNIQUE (keyword),
    CONSTRAINT chk_discovery_hashtags_keyword_normalized
        CHECK (
            keyword <> ''
            AND keyword = BTRIM(keyword)
            AND keyword = LOWER(keyword)
            AND LEFT(keyword, 1) <> '#'
        )
);

INSERT INTO discovery_hashtags (keyword, enabled, created_at, updated_at)
VALUES
    ('의사스타그램', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('약사스타그램', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('피부과', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

CREATE TABLE discovery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instagram_media_id VARCHAR(255) NOT NULL,
    media_type VARCHAR(32) NOT NULL,
    permalink VARCHAR(2048) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    first_discovered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    caption_excerpt VARCHAR(500),
    review_status VARCHAR(16) NOT NULL,
    CONSTRAINT uk_discovery_items_instagram_media_id UNIQUE (instagram_media_id),
    CONSTRAINT chk_discovery_items_review_status
        CHECK (review_status IN ('NEW', 'OPENED', 'DISMISSED')),
    CONSTRAINT chk_discovery_items_seen_order
        CHECK (last_seen_at >= first_discovered_at)
);

CREATE INDEX idx_discovery_items_review_published
    ON discovery_items (review_status, published_at DESC, id DESC);

CREATE TABLE discovery_item_hashtags (
    discovery_item_id BIGINT NOT NULL,
    discovery_hashtag_id BIGINT NOT NULL,
    PRIMARY KEY (discovery_item_id, discovery_hashtag_id),
    CONSTRAINT fk_discovery_item_hashtags_item
        FOREIGN KEY (discovery_item_id) REFERENCES discovery_items (id) ON DELETE CASCADE,
    CONSTRAINT fk_discovery_item_hashtags_hashtag
        FOREIGN KEY (discovery_hashtag_id) REFERENCES discovery_hashtags (id)
);

CREATE INDEX idx_discovery_item_hashtags_hashtag_id
    ON discovery_item_hashtags (discovery_hashtag_id);
