CREATE TABLE discovery_browser_observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discovery_item_id BIGINT NOT NULL,
    author_username VARCHAR(30),
    author_display_name VARCHAR(255),
    profile_url VARCHAR(2048),
    follower_count BIGINT,
    following_count BIGINT,
    post_count BIGINT,
    biography_excerpt VARCHAR(300),
    verified BOOLEAN,
    private_account BOOLEAN,
    post_like_count BIGINT,
    post_comment_count BIGINT,
    post_view_count BIGINT,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_code VARCHAR(64),
    error_summary VARCHAR(500),
    CONSTRAINT uk_discovery_browser_observations_item UNIQUE (discovery_item_id),
    CONSTRAINT fk_discovery_browser_observations_item
        FOREIGN KEY (discovery_item_id) REFERENCES discovery_items (id) ON DELETE CASCADE,
    CONSTRAINT chk_discovery_browser_observations_username_lowercase
        CHECK (author_username IS NULL OR author_username = LOWER(author_username)),
    CONSTRAINT chk_discovery_browser_observations_counts_nonnegative
        CHECK (
            (follower_count IS NULL OR follower_count >= 0)
            AND (following_count IS NULL OR following_count >= 0)
            AND (post_count IS NULL OR post_count >= 0)
            AND (post_like_count IS NULL OR post_like_count >= 0)
            AND (post_comment_count IS NULL OR post_comment_count >= 0)
            AND (post_view_count IS NULL OR post_view_count >= 0)
        ),
    CONSTRAINT chk_discovery_browser_observations_status
        CHECK (status IN ('SUCCESS', 'PARTIAL', 'LOGIN_REQUIRED', 'ACTION_REQUIRED', 'FAILED')),
    CONSTRAINT chk_discovery_browser_observations_error
        CHECK (
            (status IN ('SUCCESS', 'PARTIAL') AND error_code IS NULL AND error_summary IS NULL)
            OR
            (status IN ('LOGIN_REQUIRED', 'ACTION_REQUIRED', 'FAILED')
                AND error_code IS NOT NULL AND error_summary IS NOT NULL)
        )
);
